Added method "HasProperty", "HasPropertyWithValues" and "HasMethod".
FluentContracts/FluentContracts pull request #12
Opened 2024-09-15 19:39 UTC by GeorgiPopovIT

Hi! Created methods HasProperty (check if the property exists in the object), HasPropertyWithValue(check property if contains with current value), and HasMethods(check if the method exists in the object). And also added a few unit tests.

I confirm that the pull-request:

- [ X] Follows the contribution guidelines
- [ X] Is based on my own work
- [X ] Is in compliance with my employer

2024-10-08 06:55 UTC, totollygeek requested changes

2024-10-08 06:55 UTC, totollygeek commented on src/FluentContracts/Contracts/BaseContract.cs
> +    public Linker<TContract> HasProperty(string propertyName, string? message = null)
You should rename all the methods to start with `Have*`. Because it would not be grammatically correct to have `object.Must().HasProperty(...)`.

2024-10-08 06:55 UTC, totollygeek commented on src/FluentContracts/Contracts/BaseContract.cs
> +    public Linker<TContract> HasPropertyWithValue(string propertyName, object value, string? message = null)
Please, refrain from using `object` unless completely necessary. Here you can change it to:
```suggestion
    public Linker<TContract> HasPropertyWithValue<TValue>(string propertyName, TValue value, string? message = null)
```

2024-10-08 06:55 UTC, totollygeek commented on src/FluentContracts/Validators/Validator.cs
> +
Why are those here? I think you based your branch on the wrong one.

2024-10-08 06:55 UTC, totollygeek commented on src/FluentContracts/Validators/Validator.cs
Please, remove all the formatting changes in this file. It pollutes the PR. Make sure you have [EditorConfig](https://editorconfig.org/) installed and setup, since this repository uses it.

2024-10-08 06:55 UTC, totollygeek commented on src/FluentContracts/Validators/Validator.cs
> +    public static void ContainsPropertyByName(object element, string propertyName, string? message = null)
Same here with `object`. Please use a generic.

2024-10-08 06:55 UTC, totollygeek commented on src/FluentContracts/Validators/Validator.cs
> +    public static void ContainsPropertyWithValue(object element, string propertyName, object value, string? message = null)
Same => `object`

2024-10-08 06:55 UTC, totollygeek commented on src/FluentContracts/Validators/Validator.cs
> +    public static void ContainsMethod(object element, string methodName, string? message = null)
Same => `object`

2024-10-08 06:55 UTC, totollygeek commented on src/FluentContracts/Validators/Validator.cs
> +using System.Diagnostics.CodeAnalysis;
You don't need this

2024-10-08 06:55 UTC, totollygeek commented on src/FluentContracts/Contracts/BaseContract.cs
Also all of our contracts follow the `Have*` and `NotHave*` scheme. Which means that I would expect you to also add:
`NotHaveProperty`, `NotHaveMethod`, `NotHavePropertyWithValue`

2024-10-08 06:55 UTC, totollygeek commented on tests/FluentContracts.Tests/BaseContractTests.cs
All of our tests (except a few infrastructure ones) use the `TestContract` helper methods. This way, you can test a contract to succeed and fail in one method. Please use the same template.

2024-10-10 05:56 UTC, GeorgiPopovIT commented
@totollygeek thanks for the review.

2025-12-16 08:01 UTC, totollygeek commented
@GeorgiPopovIT Do you plan to go forward with this PR? If not, then I will close it.

2025-12-16 08:02 UTC, closed without merging